-- CreateEnum
CREATE TYPE "Fucao" AS ENUM ('MEDICO', 'ENFERMEIRO', 'ADMINISTRATIVO', 'RECEPCIONISTA', 'TECNICO');

-- AlterTable
ALTER TABLE "Funcionario" ALTER COLUMN "tipoDocumento" DROP NOT NULL,
ALTER COLUMN "documento" DROP NOT NULL;
